<<<<<<< HEAD
services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-elearning_platform}
    ports:
      - "5434:5432"
    volumes:
      - edutech:/var/lib/postgresql/data
      - ./apps/backend/database/elearning_platform.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-elearning_platform}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  edutech:
=======
services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-elearning_platform}
    ports:
      - "5434:5432"
    volumes:
      - edutech:/var/lib/postgresql/data
      - ./apps/backend/database/elearning_platform.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-elearning_platform}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  edutech:
>>>>>>> fedc12a308713d0f718e2b7c4093b1ac9d0d81ba
